name: app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4
  cupertino_icons: ^0.1.2
  device_preview: ^0.4.5
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  firebase_core: ^0.4.0+8
  firebase_auth: ^0.15.0+1
  flutter_modular: ^1.2.5+1
  provider: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/

  
#import 'package:mobx/mobx.dart';
#import 'package:flutter_mobx/flutter_mobx.dart';
#import 'package:mobx_codegen/mobx_codegen.dart';